export const ingredientsData = [
  {
    name: "Ail",
    months: [
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
    ],
    source: {
      name: "Bruxelles Environnement IBGE",
      link: `https://environnement.brussels/sites/default/files/calendrier_saison_fr_def_part_fr.pdf`,
    },
  },
  {
    name: "Bette",
    months: [
      false,
      false,
      false,
      false,
      false,
      "start",
      true,
      true,
      true,
      true,
      "end",
      false,
    ],
    source: {
      name: "Bruxelles Environnement IBGE",
      link: `https://environnement.brussels/sites/default/files/calendrier_saison_fr_def_part_fr.pdf`,
    },
  },
  {
    name: "Betterave",
    months: [
      true,
      true,
      "end",
      false,
      false,
      "start",
      true,
      true,
      true,
      true,
      true,
      true,
    ],
    source: {
      name: "Bruxelles Environnement IBGE",
      link: `https://environnement.brussels/sites/default/files/calendrier_saison_fr_def_part_fr.pdf`,
    },
  },
  {
    name: "Beurre",
    months: [
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
    ],
    source: {
      name: "Bruxelles Environnement IBGE",
      link: `https://environnement.brussels/sites/default/files/calendrier_saison_fr_def_part_fr.pdf`,
    },
  },
  {
    name: "Brocoli",
    months: [
      false,
      false,
      false,
      false,
      false,
      "start",
      true,
      true,
      true,
      true,
      true,
      "end",
    ],
    source: {
      name: "Bruxelles Environnement IBGE",
      link: `https://environnement.brussels/sites/default/files/calendrier_saison_fr_def_part_fr.pdf`,
    },
  },
  {
    name: "Carotte",
    months: [
      true,
      true,
      "end",
      false,
      false,
      "start",
      true,
      true,
      true,
      true,
      true,
      true,
    ],
    source: {
      name: "Bruxelles Environnement IBGE",
      link: `https://environnement.brussels/sites/default/files/calendrier_saison_fr_def_part_fr.pdf`,
    },
  },
  {
    name: "Champignon",
    months: [
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
    ],
    source: {
      name: "Bruxelles Environnement IBGE",
      link: `https://environnement.brussels/sites/default/files/calendrier_saison_fr_def_part_fr.pdf`,
    },
  },
  {
    name: "Chapelure",
    months: [
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
    ],
    source: {
      name: "Bruxelles Environnement IBGE",
      link: `https://environnement.brussels/sites/default/files/calendrier_saison_fr_def_part_fr.pdf`,
    },
  },
  {
    name: "Coriandre",
    months: [
      false,
      false,
      false,
      false,
      "start",
      true,
      true,
      true,
      true,
      "end",
      false,
      false,
    ],
    source: {
      name: "jardiner-malin.fr",
      link: `https://www.jardiner-malin.fr/fiche/coriandre.html`,
    },
  },
  {
    name: "Crème",
    months: [
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
    ],
    source: {
      name: "Bruxelles Environnement IBGE",
      link: `https://environnement.brussels/sites/default/files/calendrier_saison_fr_def_part_fr.pdf`,
    },
  },
  {
    name: "Farine",
    months: [
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
    ],
    source: {
      name: "Bruxelles Environnement IBGE",
      link: `https://environnement.brussels/sites/default/files/calendrier_saison_fr_def_part_fr.pdf`,
    },
  },
  {
    name: "Avoine",
    months: [
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
    ],
    source: {
      name: "Bruxelles Environnement IBGE",
      link: `https://environnement.brussels/sites/default/files/calendrier_saison_fr_def_part_fr.pdf`,
    },
  },
  {
    name: "Fromage",
    months: [
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
    ],
    source: {
      name: "Bruxelles Environnement IBGE",
      link: `https://environnement.brussels/sites/default/files/calendrier_saison_fr_def_part_fr.pdf`,
    },
  },
  {
    name: "Groseilles",
    months: [
      false,
      false,
      false,
      false,
      false,
      "start",
      "end",
      false,
      false,
      false,
      false,
      false,
    ],
    source: {
      name: "Bruxelles Environnement IBGE",
      link: `https://environnement.brussels/sites/default/files/calendrier_saison_fr_def_part_fr.pdf`,
    },
  },
  {
    name: "Huile végétale",
    months: [
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
    ],
    source: {
      name: "Bruxelles Environnement IBGE",
      link: `https://environnement.brussels/sites/default/files/calendrier_saison_fr_def_part_fr.pdf`,
    },
  },
  {
    name: "Lait",
    months: [
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
    ],
    source: {
      name: "Bruxelles Environnement IBGE",
      link: `https://environnement.brussels/sites/default/files/calendrier_saison_fr_def_part_fr.pdf`,
    },
  },
  {
    name: "Lentilles",
    months: [
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
    ],
    source: {
      name: "Bruxelles Environnement IBGE",
      link: `https://environnement.brussels/sites/default/files/calendrier_saison_fr_def_part_fr.pdf`,
    },
  },
  {
    name: "Miel",
    months: [
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
    ],
    source: {
      name: "Bruxelles Environnement IBGE",
      link: `https://environnement.brussels/sites/default/files/calendrier_saison_fr_def_part_fr.pdf`,
    },
  },
  {
    name: "Œuf",
    months: [
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
    ],
    source: {
      name: "Bruxelles Environnement IBGE",
      link: `https://environnement.brussels/sites/default/files/calendrier_saison_fr_def_part_fr.pdf`,
    },
  },
  {
    name: "Oignon",
    months: [
      true,
      true,
      "end",
      false,
      false,
      false,
      "start",
      true,
      true,
      true,
      true,
      true,
    ],
    source: {
      name: "Bruxelles Environnement IBGE",
      link: `https://environnement.brussels/sites/default/files/calendrier_saison_fr_def_part_fr.pdf`,
    },
  },
  {
    name: "Orge",
    months: [
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
    ],
    source: {
      name: "Bruxelles Environnement IBGE",
      link: `https://environnement.brussels/sites/default/files/calendrier_saison_fr_def_part_fr.pdf`,
    },
  },
  {
    name: "Ortie",
    months: [
      false,
      false,
      false,
      false,
      false,
      "start",
      true,
      true,
      "end",
      false,
      false,
      false,
    ],
    source: {
      name: "medadvicees.com",
      link: `https://medadvicees.com/fr/pages/13103`,
    },
  },
  {
    name: "Patate",
    months: [
      true,
      true,
      true,
      "end",
      false,
      "start",
      true,
      true,
      true,
      true,
      true,
      true,
    ],
    source: {
      name: "Bruxelles Environnement IBGE",
      link: `https://environnement.brussels/sites/default/files/calendrier_saison_fr_def_part_fr.pdf`,
    },
  },
  {
    name: "Pomme",
    months: [
      true,
      true,
      "end",
      false,
      false,
      false,
      false,
      "start",
      true,
      true,
      true,
      true,
    ],
    source: {
      name: "Bruxelles Environnement IBGE",
      link: `https://environnement.brussels/sites/default/files/calendrier_saison_fr_def_part_fr.pdf`,
    },
  },
  {
    name: "Quinoa",
    months: [
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
    ],
    source: {
      name: "Bruxelles Environnement IBGE",
      link: `https://environnement.brussels/sites/default/files/calendrier_saison_fr_def_part_fr.pdf`,
    },
  },
  {
    name: "Rhubarbe",
    months: [
      false,
      false,
      false,
      "start",
      true,
      true,
      true,
      "end",
      false,
      false,
      false,
      false,
    ],
    source: {
      name: "Bruxelles Environnement IBGE",
      link: `https://environnement.brussels/sites/default/files/calendrier_saison_fr_def_part_fr.pdf`,
    },
  },
  {
    name: "Sarriette",
    months: [
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
    ],
    source: {
      name: "Bruxelles Environnement IBGE",
      link: `https://environnement.brussels/sites/default/files/calendrier_saison_fr_def_part_fr.pdf`,
    },
  },
  {
    name: "Sucre",
    months: [
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
    ],
    source: {
      name: "Bruxelles Environnement IBGE",
      link: `https://environnement.brussels/sites/default/files/calendrier_saison_fr_def_part_fr.pdf`,
    },
  },
  {
    name: "Tomate",
    months: [
      false,
      false,
      false,
      false,
      false,
      false,
      "start",
      true,
      true,
      "end",
      false,
      false,
    ],
    source: {
      name: "Bruxelles Environnement IBGE",
      link: `https://environnement.brussels/sites/default/files/calendrier_saison_fr_def_part_fr.pdf`,
    },
  },
]
